spring.application.name=khatabook
spring.datasource.url=jdbc:mysql://localhost:3306/khata_book
spring.datasource.username=root
spring.datasource.password=Hardik@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.port=8080



logging.file.name=C:/Temp/inventory-management.log

logging.level.root=INFO
logging.level.com.GTC.khatabook=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE